import { useMemo, useState } from 'react';
import { Check, ChevronDown, Loader2, RefreshCw } from 'lucide-react';

export default function ScriptReview({ initialScript, sources, busy, onApprove, onRewrite }: { initialScript: string; sources: string[]; busy: boolean; onApprove: (script: string) => void; onRewrite: (direction: string) => void }) {
  const [script, setScript] = useState(initialScript); const [direction, setDirection] = useState(''); const [showSources, setShowSources] = useState(false); const words = useMemo(() => script.trim().split(/\s+/).filter(Boolean).length, [script]);
  return <div className="mx-auto max-w-5xl px-6 py-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--space-text-brand)]">Step 2 · Script review</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold text-[var(--space-text-primary)]">Make every word yours</h1><p className="mt-1 text-[var(--space-text-secondary)]">Edit freely, then approve before any paid video render begins.</p></div><div className="rounded-full bg-[var(--space-surface-muted)] px-3 py-1.5 text-sm text-[var(--space-text-secondary)]">{words} words · ~{Math.max(1, Math.round(words / 130))} min</div></div>
    <textarea value={script} onChange={(e) => setScript(e.target.value)} className="mt-6 min-h-[420px] w-full rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-card)] p-6 text-base leading-7 text-[var(--space-text-primary)] outline-none focus:border-[var(--space-brand-primary-500)]" />
    <button onClick={() => setShowSources(!showSources)} className="mt-3 flex items-center gap-2 text-sm text-[var(--space-text-secondary)]"><ChevronDown className={`h-4 w-4 transition ${showSources ? 'rotate-180' : ''}`} /> Sources ({sources.length})</button>{showSources ? <ul className="mt-2 space-y-1 rounded-xl bg-[var(--space-surface-panel)] p-4 text-sm text-[var(--space-text-muted)]">{sources.length ? sources.map((source) => <li key={source} className="break-all">{source}</li>) : <li>No source URLs were returned.</li>}</ul> : null}
    <div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input value={direction} onChange={(e) => setDirection(e.target.value)} placeholder="Optional rewrite direction: sharper hook, warmer tone…" className="rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-4 py-3 text-[var(--space-text-primary)]" /><button disabled={busy} onClick={() => onRewrite(direction)} className="flex items-center justify-center gap-2 rounded-xl border border-[var(--space-border-strong)] px-4 py-3 text-[var(--space-text-primary)]">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Rewrite</button><button disabled={busy || !script.trim()} onClick={() => onApprove(script)} className="flex items-center justify-center gap-2 rounded-xl bg-[var(--space-brand-primary-600)] px-5 py-3 font-semibold text-white"><Check className="h-4 w-4" /> Looks good — approve</button></div>
  </div>;
}
