import { useState } from 'react';
import { ArrowRight, Loader2, Sparkles } from 'lucide-react';

export default function TopicInput({ busy, onStart }: { busy: boolean; onStart: (input: { topic: string; audience?: string; language: string; target_length_sec: number; aspect_ratio: '16:9' | '9:16' }) => void }) {
  const [topic, setTopic] = useState(''); const [audience, setAudience] = useState(''); const [language, setLanguage] = useState('en'); const [customLanguage, setCustomLanguage] = useState(''); const [minutes, setMinutes] = useState(5); const [ratio, setRatio] = useState<'16:9' | '9:16'>('16:9');
  return <div className="mx-auto max-w-3xl px-6 py-12">
    <div className="mb-8 flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--space-surface-accent-soft)]"><Sparkles className="h-6 w-6 text-[var(--space-text-brand)]" /></div>
    <p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--space-text-brand)]">Step 1 of 8</p><h1 className="mt-2 text-3xl font-bold text-[var(--space-text-primary)]">What should Verger explain?</h1><p className="mt-2 text-[var(--space-text-secondary)]">Start with the idea. The research agent turns it into a natural presenter script.</p>
    <textarea value={topic} onChange={(e) => setTopic(e.target.value)} rows={7} placeholder="Explain why cities are getting hotter, using memorable examples and practical takeaways…" className="mt-7 w-full rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-card)] p-5 text-lg leading-relaxed text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" />
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-[var(--space-text-secondary)]">Audience<input value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="Curious non-experts" className="mt-1.5 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" /></label><label className="text-sm font-medium text-[var(--space-text-secondary)]">Language<select value={language} onChange={(e) => setLanguage(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]"><option value="en">English</option><option value="hi">Hindi</option><option value="hinglish">Hinglish</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="custom">Other…</option></select></label></div>
    {language === 'custom' ? <input value={customLanguage} onChange={(e) => setCustomLanguage(e.target.value)} placeholder="Language name or code" className="mt-3 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" /> : null}
    <div className="mt-5 rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] p-4"><div className="flex justify-between text-sm text-[var(--space-text-secondary)]"><span>Target length</span><strong className="text-[var(--space-text-primary)]">{minutes} min</strong></div><input type="range" min={1} max={15} value={minutes} onChange={(e) => setMinutes(Number(e.target.value))} className="mt-3 w-full" /><div className="mt-4 flex gap-2">{(['16:9','9:16'] as const).map((r) => <button key={r} onClick={() => setRatio(r)} className={`rounded-lg px-4 py-2 text-sm font-medium transition-all focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--space-brand-primary-500)] ${ratio === r ? 'bg-[var(--space-brand-primary-600)] text-white shadow-[0_2px_8px_color-mix(in_srgb,var(--space-brand-primary-600)_40%,transparent)]' : 'bg-[var(--space-surface-muted)] text-[var(--space-text-secondary)] hover:bg-[color-mix(in_srgb,var(--space-text-primary)_8%,var(--space-surface-muted))] hover:text-[var(--space-text-primary)]'}`}>{r} {r === '16:9' ? 'Landscape' : 'Portrait'}</button>)}</div></div>
    <button disabled={busy || topic.trim().length < 10} onClick={() => onStart({ topic: topic.trim(), audience: audience.trim(), language: language === 'custom' ? customLanguage.trim() || 'en' : language, target_length_sec: minutes * 60, aspect_ratio: ratio })} className="mt-6 flex items-center gap-2 rounded-xl bg-[var(--space-brand-primary-600)] px-5 py-3 font-semibold text-white shadow-[0_2px_12px_color-mix(in_srgb,var(--space-brand-primary-600)_40%,transparent)] transition-all hover:-translate-y-0.5 hover:bg-[var(--space-brand-primary-700)] hover:shadow-[0_6px_18px_color-mix(in_srgb,var(--space-brand-primary-600)_50%,transparent)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--space-brand-primary-500)] disabled:opacity-40 disabled:shadow-none disabled:hover:translate-y-0">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />} {busy ? 'Researching…' : 'Research & Write Script'}</button>
  </div>;
}
