import { useState } from 'react';
import { ArrowRight, Film, Loader2, Sparkles, Upload } from 'lucide-react';
import { EDITING_PRESETS, type EditingPresetId } from '../styles/registry';
import { WORKSPACE_ID } from '../lib/supabase';

type StartInput = { topic: string; audience?: string; language: string; target_length_sec: number; aspect_ratio: '16:9' | '9:16'; editing_preset?: EditingPresetId; reference_video_url?: string; reference_style_analysis?: Record<string, unknown> };

export default function TopicInput({ busy, onStart }: { busy: boolean; onStart: (input: StartInput) => void }) {
  const [topic, setTopic] = useState(''); const [audience, setAudience] = useState(''); const [language, setLanguage] = useState('en'); const [customLanguage, setCustomLanguage] = useState(''); const [minutes, setMinutes] = useState(5); const [ratio, setRatio] = useState<'16:9' | '9:16'>('9:16');
  const [preset, setPreset] = useState<EditingPresetId>('documentary');
  const [referenceName, setReferenceName] = useState('');
  const [referenceUrl, setReferenceUrl] = useState('');
  const [referenceAnalysis, setReferenceAnalysis] = useState<Record<string, unknown> | null>(null);
  const [referenceBusy, setReferenceBusy] = useState(false);
  const [referenceError, setReferenceError] = useState('');

  const analyzeReference = async (file: File) => {
    if (file.size > 50 * 1024 * 1024) { setReferenceError('Keep the optional reference under 50 MB. A short sample is enough to learn its editing language.'); return; }
    setReferenceBusy(true); setReferenceError(''); setReferenceName(file.name); setReferenceAnalysis(null);
    try {
      const upload = new FormData(); upload.append('file', file); upload.append('workspaceId', WORKSPACE_ID); upload.append('folder', 'sceneforge-reference');
      const token = String((window as any).__workspaceDb?.token || '');
      const storedResponse = await fetch('/api/upload/file', { method: 'POST', headers: token ? { 'X-Workspace-DB-Token': token } : undefined, body: upload });
      const stored = await storedResponse.json();
      if (!storedResponse.ok || !stored.url) throw new Error(stored.error || 'Reference upload failed');
      const analysisForm = new FormData(); analysisForm.append('file', file); analysisForm.append('prompt', 'Analyze only this reference video editing LANGUAGE, never its assets or identity. Sample the full clip and transcribe a concise excerpt. Return strict JSON with keys: summary, cut_frequency, average_shot_length_sec, graphic_density, caption_behavior, pacing, camera_language, transition_language, broll_pattern, speaker_visibility_rules, transcript_excerpt, and transferable_rules (array of 4-8 concise rules). Describe what a new edit should imitate structurally. Do not suggest copying people, footage, music, logos, words, or visual assets from this video.');
      const analyzedResponse = await fetch('/api/generate/video-analysis', { method: 'POST', body: analysisForm });
      const analyzed = await analyzedResponse.json();
      if (!analyzedResponse.ok || !analyzed.success) throw new Error(analyzed.error || 'Reference analysis failed');
      let parsed: Record<string, unknown>;
      try { parsed = JSON.parse(String(analyzed.result || '').replace(/^```json\s*|\s*```$/g, '')); }
      catch { parsed = { summary: String(analyzed.result || ''), source: 'gemini_video_understanding' }; }
      setReferenceUrl(String(stored.url)); setReferenceAnalysis(parsed);
    } catch (error: any) { setReferenceUrl(''); setReferenceError(error.message || 'Could not analyze that reference video.'); }
    finally { setReferenceBusy(false); }
  };
  return <div className="mx-auto max-w-3xl px-6 py-12">
    <div className="mb-8 flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--space-surface-accent-soft)]"><Sparkles className="h-6 w-6 text-[var(--space-text-brand)]" /></div>
    <p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--space-text-brand)]">Step 1 of 8</p><h1 className="mt-2 text-3xl font-bold text-[var(--space-text-primary)]">What should Verger explain?</h1><p className="mt-2 text-[var(--space-text-secondary)]">Start with the idea. The research agent turns it into a natural presenter script.</p>
    <textarea value={topic} onChange={(e) => setTopic(e.target.value)} rows={7} placeholder="Explain why cities are getting hotter, using memorable examples and practical takeaways…" className="mt-7 w-full rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-card)] p-5 text-lg leading-relaxed text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" />
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-[var(--space-text-secondary)]">Audience<input value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="Curious non-experts" className="mt-1.5 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" /></label><label className="text-sm font-medium text-[var(--space-text-secondary)]">Language<select value={language} onChange={(e) => setLanguage(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]"><option value="en">English</option><option value="hi">Hindi</option><option value="hinglish">Hinglish</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="custom">Other…</option></select></label></div>
    {language === 'custom' ? <input value={customLanguage} onChange={(e) => setCustomLanguage(e.target.value)} placeholder="Language name or code" className="mt-3 w-full rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] px-3 py-2.5 text-[var(--space-text-primary)] outline-none transition-colors placeholder:text-[var(--space-text-muted)] focus:border-[var(--space-brand-primary-500)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--space-brand-primary-500)_22%,transparent)]" /> : null}
    <div className="mt-5 rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] p-4"><div className="flex justify-between text-sm text-[var(--space-text-secondary)]"><span>Target length</span><strong className="text-[var(--space-text-primary)]">{minutes} min</strong></div><input type="range" min={1} max={15} value={minutes} onChange={(e) => setMinutes(Number(e.target.value))} className="mt-3 w-full" /><div className="mt-4 flex gap-2">{(['9:16','16:9'] as const).map((r) => <button key={r} onClick={() => setRatio(r)} className={`rounded-lg px-4 py-2 text-sm font-medium transition-all focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--space-brand-primary-500)] ${ratio === r ? 'bg-[var(--space-brand-primary-600)] text-white shadow-[0_2px_8px_color-mix(in_srgb,var(--space-brand-primary-600)_40%,transparent)]' : 'bg-[var(--space-surface-muted)] text-[var(--space-text-secondary)] hover:bg-[color-mix(in_srgb,var(--space-text-primary)_8%,var(--space-surface-muted))] hover:text-[var(--space-text-primary)]'}`}>{r} {r === '16:9' ? 'Landscape' : 'Portrait full-face'}</button>)}</div></div>
    <section className="mt-5 rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] p-4">
      <div className="flex items-center gap-2"><Film className="h-4 w-4 text-[var(--space-text-brand)]" /><h2 className="font-semibold text-[var(--space-text-primary)]">Editing strategy</h2></div>
      <p className="mt-1 text-sm text-[var(--space-text-secondary)]">This controls pacing, B-roll frequency, graphics and captions. You will still choose the visual skin later.</p>
      <div className="mt-3 grid gap-2 sm:grid-cols-2">{EDITING_PRESETS.map((item) => <button key={item.id} type="button" onClick={() => setPreset(item.id)} className={preset === item.id ? 'rounded-xl border border-[var(--space-brand-primary-500)] bg-[color-mix(in_srgb,var(--space-brand-primary-500)_12%,transparent)] p-3 text-left' : 'rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-card)] p-3 text-left hover:border-[var(--space-border-strong)]'}><span className="block text-sm font-semibold text-[var(--space-text-primary)]">{item.name}</span><span className="mt-1 block text-xs leading-5 text-[var(--space-text-muted)]">{item.description}</span></button>)}</div>
    </section>
    <section className="mt-5 rounded-2xl border border-[var(--space-border-default)] bg-[var(--space-surface-panel)] p-4">
      <div className="flex items-center gap-2"><Upload className="h-4 w-4 text-[var(--space-text-brand)]" /><h2 className="font-semibold text-[var(--space-text-primary)]">Reference video <span className="font-normal text-[var(--space-text-muted)]">· optional</span></h2></div>
      <p className="mt-1 text-sm text-[var(--space-text-secondary)]">Upload a short clip to learn its cut rhythm, graphic density, caption behavior and pacing. SceneForge applies the language only — never the footage, people, music or assets.</p>
      <label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border border-[var(--space-border-default)] bg-[var(--space-surface-card)] px-4 py-2.5 text-sm font-semibold text-[var(--space-text-primary)] hover:border-[var(--space-border-strong)]">{referenceBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}{referenceBusy ? 'Sampling & transcribing…' : referenceName || 'Choose short video'}<input type="file" accept="video/mp4,video/webm,video/quicktime" className="hidden" disabled={referenceBusy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void analyzeReference(file); event.currentTarget.value = ''; }} /></label>
      {referenceAnalysis ? <p className="mt-3 rounded-lg bg-[color-mix(in_srgb,var(--space-semantic-success-500)_10%,transparent)] p-3 text-xs text-[var(--space-text-secondary)]">Reference language ready: {String(referenceAnalysis.summary || 'cuts, graphics, captions and pacing analyzed')}.</p> : null}
      {referenceError ? <p className="mt-3 text-sm text-[var(--space-semantic-danger)]">{referenceError}</p> : null}
    </section>
    <button disabled={busy || referenceBusy || topic.trim().length < 10} onClick={() => { (window as any).__sceneForgePlanningContext = { editingPreset: preset, referenceVideoUrl: referenceUrl || null, referenceStyleAnalysis: referenceAnalysis }; onStart({ topic: topic.trim(), audience: audience.trim(), language: language === 'custom' ? customLanguage.trim() || 'en' : language, target_length_sec: minutes * 60, aspect_ratio: ratio, editing_preset: preset, ...(referenceUrl && referenceAnalysis ? { reference_video_url: referenceUrl, reference_style_analysis: referenceAnalysis } : {}) }); }} className="mt-6 flex items-center gap-2 rounded-xl bg-[var(--space-brand-primary-600)] px-5 py-3 font-semibold text-white shadow-[0_2px_12px_color-mix(in_srgb,var(--space-brand-primary-600)_40%,transparent)] transition-all hover:-translate-y-0.5 hover:bg-[var(--space-brand-primary-700)] hover:shadow-[0_6px_18px_color-mix(in_srgb,var(--space-brand-primary-600)_50%,transparent)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--space-brand-primary-500)] disabled:opacity-40 disabled:shadow-none disabled:hover:translate-y-0">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />} {busy ? 'Researching…' : 'Research & Write Script'}</button>
  </div>;
}
